### ISSUE TITLE
images are absent from manifest

### ISSUE THREAD

**Issue by quantix-studio** [mariusbalcytis/extract-file-loader#1]
Hi,

I use the initial config to manage images : 

```
    config.module = {
        preLoaders: [{
            // query string is needed for URLs inside css files, like bootstrap
            test: /\.(gif|png|jpe?g|svg)(\?.*)?$/i,
            loader: 'image-webpack'
        }],
        loaders: [{
            // JS LOADER
            // Reference: https://github.com/babel/babel-loader
            // Transpile .js files using babel-loader
            // Compiles ES6 and ES7 into ES5 code
            test: /\.jsx?$/i,
            loaders: ['babel'],
            exclude: /node_modules/
        }, {
            // ASSET LOADER
            // Reference: https://github.com/webpack/file-loader
            // Copy png, jpg, jpeg, gif, svg, woff, woff2, ttf, eot files to output
            // Rename the file using the asset hash
            // Pass along the updated reference to your code
            // You can add here any file extension you want to get copied to your output

            // query string is needed for URLs inside css files, like bootstrap
            test: /\.(png|jpe?g|gif|svg|woff2?|ttf|eot)(\?.*)?$/i,

            // put original name in the destination filename, too
            loader: 'file?name=[name].[hash].[ext]'
        }, {
            // HTML LOADER
            // Reference: https://github.com/webpack/raw-loader
            // Allow loading html through js
            test: /\.html$/i,
            loader: 'raw'
        }]
    };
```

and 
`webpack_asset('path/to/img')`
in my twig file, but the image is not dumped in the manifest and I get the error : 
An exception has been thrown during the rendering of a template ("No information in manifest for @user/images/bg-7-1.jpg (key bg-7-1-4c425e9cc487a6ef515e39b0d5ef254176ea5b3d). Is maba:webpack:dev-server running in the background?")

What am I doing wrong ?

**Comment by mariusbalcytis** [comment]
Is `maba:webpack:dev-server` running? Does it give any errors?

**Comment by quantix-studio** [comment]
It's OK when I am using 'webpack_asset(img)' from the twig root-template.
From a sub-template it fails (console tells me server is running ok, but no localhost:8080 in chrome inspector 'sources' tab, and no img in manifest.

**Comment by quantix-studio** [comment]
if I 
    {% set img %}
        {{ webpack_asset('@bundle/path/to/image.jpg') }}
    {% endset %}
in the root tpl and then call the img var in sub-tpl, then it's OK.

Is it the way to proceed ? I find it a bit weird...

**Comment by quantix-studio** [comment]
Ok found the solution. 
In the conf file, asset_providers > resource, I had to list the bundles used (seems to fail defaulting all modules by default in my case).

Big thank for your precious work !

**Comment by mariusbalcytis** [comment]
Just for the reference - did you have something defined in `asset_providers` in your configuration?

Default behavior is that if you define at least something in `asset_providers`, it overwrites any default values, so if you've provided some custom directory, all bundles are not scanned.

If that was the case, maybe some improvements in documentation could be made (or behavior itself).

**Comment by quantix-studio** [comment]
I had : 
`    asset_providers:    # if you overwrite this, be sure to explicitly provide needed configuration like all bundles`
`        -`
`            type:                 twig_bundles  # analyses twig templates inside given bundles`
`             resource:             [] # all by default`
       ` -`
            `type:                 twig_directory # analyses twig templates inside given directory`
            `resource:             %kernel.root_dir%/Resources/views`


Explicitly setting 
`            resource:             # all by default`
                `- UserBundle`
                `- AppBundle
`
solved the problem
