### ISSUE TITLE
Installation instruction use wrong package name?

### ISSUE THREAD

**Issue by antonyoneill** [mariusbalcytis/extract-file-loader#7]
Hey Marius,

The installation instructions here state that to install the package, you should install `extract-text-webpack-plugin` - not sure that's right? Or are you suggesting that this package is now replaced by https://github.com/webpack-contrib/extract-text-webpack-plugin?

**Comment by mariusbalcytis** [comment]
No, probably just copy-pasted from extract-text-webpack-plugin, which was a bootstrap to start from.

Thanks, fixed.

**Comment by antonyoneill** [comment]
Lovely thanks
